service: poff-api

provider:
    name: aws
    runtime: nodejs12.x
    stage: prod
    stackName: ${self:provider.stage}-${self:service}
    apiName: ${self:provider.stage}-${self:service}
    region: eu-central-1
    endpointType: regional
    memorySize: 256
    timeout: 21
    logRetentionInDays: 365
    httpApi:
        cors: true
        payload: '2.0'
    logs:
        httpApi: true
    # tracing:
    #     lambda: true

    deploymentBucket:
        name: ${self:service}
        serverSideEncryption: AES256

    environment:
        GIT_BRANCH: ${git:branch}
        GIT_SHA1: ${git:sha1}

layers:
    commonNodeLibs:
        path: layers
        compatibleRuntimes:
            - nodejs12.x

package:
    individually: true
    exclude:
        - layers/**
        - node_modules/**
        - src/**
        - '*'

plugins:
    - serverless-plugin-git-variables

custom:
    exportGitVariables: false

functions:
    version:
        handler: src/version.handler
        name: ${self:provider.stage}-${self:service}-version
        description: Returns current code branch name and commit
        package:
            include:
                - src/version.js
        layers:
            - {Ref: CommonNodeLibsLambdaLayer}
        events:
            -
                httpApi: GET /
            -
                httpApi: GET /version

    codeForTokens:
        handler: src/codeForTokens.handler
        name: ${self:provider.stage}-${self:service}-codeForTokens
        description:
        package:
            include:
                - src/codeForTokens.js
        layers:
            - {Ref: CommonNodeLibsLambdaLayer}
        events:
            -
                httpApi: GET /codeForTokens

    verif:
        handler: src/verif.handler
        name: ${self:provider.stage}-${self:service}-verif
        description:
        package:
            include:
                - src/verif.js
        layers:
            - {Ref: CommonNodeLibsLambdaLayer}
        events:
            -
                httpApi: GET /verif

    tkns:
        handler: src/tkns.handler
        name: ${self:provider.stage}-${self:service}-tkns
        description:
        package:
            include:
                - src/tkns.js
        layers:
            - {Ref: CommonNodeLibsLambdaLayer}
        events:
            -
                httpApi: GET /tkns

    markQnrAsUnfilled:
        handler: src/markQnrAsUnfilled.handler
        name: ${self:provider.stage}-${self:service}-markQnrAsUnfilled
        description:
        package:
            include:
                - src/markQnrAsUnfilled.js
        layers:
            - {Ref: CommonNodeLibsLambdaLayer}
        events:
            -
                httpApi: GET /markQnrAsUnfilled
